version: '3'
services:
    hakoonnna:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "hakoonnna"
        volumes:
            - ../:/usr/src/app
        tty: true
        ports:
            - "3000:3000"
        # links:
        #     - mongo
        environment:
            VIRTUAL_HOST: hako-onnna.local.jp

    # mongo:
    #     container_name: mongo
    #     image: mongo
    #     volumes:
    #         - ./data:/data/db
    #     ports:
    #         - "27017:27017"
